### ISSUE TITLE
Sketch alters pwm parameter - Why?

### ISSUE THREAD

**Issue by heuer** [PeterDHabermehl/ftduino_direct#4]
I defined in my script a max. PWM value of 62 (see ftduino.h and manual)

But if I send this value via ```output set``` with a light connected to O1, the light just glows.
If I send the value via ```motor_set```, the motor runs slowly. 

I found the problem in the following lines:

https://github.com/PeterDHabermehl/ftduino_direct/blob/24bc193cc1466f5e753d1f6cd9765396c764a58e/ftduino_direct/ftduino_direct.ino#L162

https://github.com/PeterDHabermehl/ftduino_direct/blob/24bc193cc1466f5e753d1f6cd9765396c764a58e/ftduino_direct/ftduino_direct.ino#L197

https://github.com/PeterDHabermehl/ftduino_direct/blob/24bc193cc1466f5e753d1f6cd9765396c764a58e/ftduino_direct/ftduino_direct.ino#L259

All commands alter the source pwm value.

Why was that done? 

IMO a 
```
     int pwm = atoi(parm3);
```
should be sufficient.

**Comment by PeterDHabermehl** [comment]
Have to check...

**Comment by PeterDHabermehl** [comment]
I don't know why you set a max. PWM value... This is a parameter describing the hw capabilities of the ftduino and should not be altered.
The ftduino_direct code lines cited by you just scale an input pwm value range (0..512) to the actual hardware capabilities just in case they might change, so you would not have to adopt your code.

**Comment by PeterDHabermehl** [comment]
But of course you're right, altering the PWM value is at least unexpected... Probably the issue arises from the lack of documentation.

**Comment by heuer** [comment]
> I don't know why you set a max. PWM value... This is a parameter describing the hw capabilities of the ftduino and should not be altered.

I use a max. constant value to avoid concrete numbers in my code. So, if the PWM value changes in the future, I just have to change the PWM constant. Acc. to the examples in the manual it's recommended to use the PWM or MAX constant (I have to look into the manual again, I guess both values are defined) rather than a concrete number. I want to do the same while communicating with ftduino_direct. Since I don't have access to the constant defined by Ftduino.h, I have to create my own MAX or PWM constant with the same value.

For example, the motor at M1 should run left with half speed:
`
ftd.comm('motor_set M1 left {0}'.format(MY_PWM_CONSTANT / 2))
`
I guess, the 512 comes from the TXT. I looked into the ftroboto lib and they use it as maxiumum value.

**Comment by PeterDHabermehl** [comment]
right ... with the same value, not 62...  set your max_value to 512 and you're good.

And actually ftduino_direct makes your idea obsolete since it abstracts from the actual hardware capabilities of the ftduino and always uses 0..512 ticks resolution for the pwm value  (yes, indeed based on the TXT and somewhat nonsense since 9bit would be 0..511, but they indeed use 0..512) and scales it to the hw capabilities exactly by the lines you cited.

btw, the motor rpm is not linear dependent on the pwm ratio or voltage.

**Comment by PeterDHabermehl** [comment]
The examples are valid for an arduino script, where the system constant is available. My first idea was to make it accessible via ftduino_direct, so you could use it in your python script, but Till proposed to handle the scaling inside ftduino_direct instead, which I did.

**Comment by heuer** [comment]
> right ... with the same value, not 62... set your max_value to 512 and you're good.

Okay, I looked into the ftDuino manual and into the Ftduino.h, so I assumed that 64 (not 62, sorry for mixing up the numbers) is the correct max. value

> ftduino and always uses 0..512 ticks resolution for the pwm value
> The examples are valid for an arduino script, where the system constant is available. My first idea was to make it accessible via ftduino_direct, so you could use it in your python script, but Till proposed to handle the scaling inside ftduino_direct instead, which I did.

Aha! That must be documented. 

In my opinion it is a bit surprising since, to my knowledge, it is not mentioned anywhere and I've gotten the impression that you can use the examples in the ftDuino manual nearly one to one.

Anyway, thanks for taking the time and for the explanation.

**Comment by PeterDHabermehl** [comment]
No matter. Actually you're the first known user, so that might one reason why I had no motivation to do any additional documentation.
BTW, I mixed some things in my before comments. 
It's 64 ticks resolution on the ftDuino, and when I started writing ftduino_direct, I had some discussion with Till and he mentioned that future versions of the ftDuino might get a higher resolution. So I decided to scale the input and do the conversions internally to ensure that python scripts using ftduino_direct will be backwards compatible in case of future changes. This was important for my App startIDE...
